export const columns = [
   {name: 'No', uid: 'id'},
   {name: 'TIME', uid: 'time'},
   {name: 'CURRENT', uid: 'current'},
   {name: 'STATUS', uid: 'statusCurrent'},
   {name: 'PRESSURE', uid: 'pressure'},
   {name: 'STATUS', uid: 'statusPressure'},
];
export const sensor = [
   {
      id: 1,
      time: '10:00:59',
      date: '19-09-2024',
      current: '2.3 A',
      statusCurrent: 'low',
      pressure: "3.5 bar",
      statusPressure: 'normal',
   },
   {
      id: 2,
      time: '10:00:59',
      date: '19-09-2024',
      current: '4 A',
      statusCurrent: 'normal',
      pressure: "4.1 bar",
      statusPressure: 'over',
   },
   {
      id: 3,
      time: '10:00:59',
      date: '19-09-2024',
      current: '3.4 A',
      statusCurrent: 'normal',
      pressure: "3.9 bar",
      statusPressure: 'normal',
   },
   {
      id: 4,
      time: '10:00:59',
      date: '19-09-2024',
      current: '2.9 A',
      statusCurrent: 'low',
      pressure: "3.7 bar",
      statusPressure: 'normal',
   },
   {
      id: 5,
      time: '10:00:59',
      date: '19-09-2024',
      current: '3.1 A',
      statusCurrent: 'normal',
      pressure: "3.8 bar",
      statusPressure: 'normal',
   },
   {
      id: 6,
      time: '10:00:59',
      date: '19-09-2024',
      current: '2.7 A',
      statusCurrent: 'low',
      pressure: "3.6 bar",
      statusPressure: 'normal',
   },
   {
      id: 7,
      time: '10:00:59',
      date: '19-09-2024',
      current: '2.5 A',
      statusCurrent: 'low',
      pressure: "3.5 bar",
      statusPressure: 'normal',
   },
   {
      id: 8,
      time: '10:00:59',
      date: '19-09-2024',
      current: '2.3 A',
      statusCurrent: 'low',
      pressure: "3.5 bar",
      statusPressure: 'normal',
   },
   {
      id: 9,
      time: '10:00:59',
      date: '19-09-2024',
      current: '5.4 A',
      statusCurrent: 'over',
      pressure: "2.4 bar",
      statusPressure: 'low',
   },
   {
      id: 10,
      time: '10:00:59',
      date: '19-09-2024',
      current: '2.3 A',
      statusCurrent: 'low',
      pressure: "3.5 bar",
      statusPressure: 'normal',
   },
   ];
